### PR TITLE
Update baseline_resync branch with latest commits

### PR DESCRIPTION
**Pull request by koujl**

### CODE REVIEW

**Comment by xiaoxichen** [comment]
I think you can rebase and force push @yuwmao

**Comment by yuwmao** [comment]
> I think you can rebase and force push @yuwmao

Yes, we should have permission, but I think @koujl prefer to use merge and it works as well.

**Comment by yuwmao** [comment]
We also need to make some changes to PGBlobIterator, I left some TODO in the PGBlobIterator.

**Comment by koujl** [comment]
Fixed TODOs in PGBlobIterator

https://github.com/eBay/HomeObject/compare/5070584461ad9ba71c436f6d40ea322cf0f3e811..5e09bc8048923aac5fff7f4c5b3bc652f8d64db8

**Comment by koujl** [comment]
This PR simply merged the latest commits into the feature branch.

Let's leave further changes / bug fixes to the next PR for simplicity.

**Review by yuwmao — APPROVED** [review]
LGTM

**Pull request merged**
