### PR TITLE
Adaptive changes for HttpManager

### PR DESCRIPTION
**Pull request by yuwmao**
Relevant changes: https://github.com/eBay/IOManager/pull/100

### CODE REVIEW

**Comment by xiaoxichen** [comment]
seem like you forgot the change on conanfile.py

**Review by raakella1 — CHANGES_REQUESTED** [review]
Can you fix this https://github.com/eBay/HomeObject/blob/4d999d4c1d8173a319f5b39946ccdf6af5bb5924/src/lib/homestore_backend/hs_homeobject.cpp#L117
This will restart http server and pass empty value for certs. We should only start http server once in SM. This restart should be removed

**Comment by yuwmao** [comment]
> Can you fix this
> 
> https://github.com/eBay/HomeObject/blob/4d999d4c1d8173a319f5b39946ccdf6af5bb5924/src/lib/homestore_backend/hs_homeobject.cpp#L117
> 
> 
> This will restart http server and pass empty value for certs. We should only start http server once in SM. This restart should be removed

Sure.

**Comment by yuwmao** [comment]
> seem like you forgot the change on conanfile.py

Yes, changed.

**Review by xiaoxichen — APPROVED** [review]

**Pull request merged**
