### PR TITLE
Remove http_server start logic

### PR DESCRIPTION
**Pull request by yuwmao**
Http_server should be started in SM, otherwise sm will crash due to setup twice.

### CODE REVIEW

**Comment by yuwmao** [comment]
@xiaoxichen @hkadayam

**Comment by zhiteng** [comment]
The start of HTTP server in HO is redundant/unnecessary as SM already did that.

**Review by hkadayam — DISMISSED** [review]
Please update the conanfile.py version on every PR.

**Comment by yuwmao** [comment]
> Please update the conanfile.py version on every PR.

Sure, updated.

**Comment by xiaoxichen** [comment]
I am not sure about why the  regression in `HomeObjectFixture.BasicPutGetDelBlobWRestart`  get on and off, but as far as it has nothing to do with this pr, lets merge it

**Review by xiaoxichen — APPROVED** [review]

**Pull request merged**
